# Code of Conduct

The Zipkin lab maintains an inclusive culture. We value the participation of every member of our community and want to ensure that each lab member and collaborator has a positive, educational experience unhindered by unneccesary challenges caused by non-inclusive behavior. Accordingly, everyone who participates in any Zipkin Lab project is expected to show respect and courtesy to other community members at all time.

We ask all members of the community to conform to the following Code of Conduct:

* Be kind to others and behave professionally.

* All communication - online and in person - should be appropriate for a professional audience including people of many different backgrounds. 

* Please make an effort to make an inclusive environment for everyone. Give everyone a chance to talk and an opportunity to contribute.

* NOTE: Your work in this lab will be publicly available and recorded permanently on github. Please conduct yourself accordingly.

The Zipkin Lab is dedicated to a harassment-free experience for everyone. Discrimination or harassment based on racial or ethnic background, citizenship status, religion (or lack thereof), political affiliation, gender identity/expression, sexual orientation, dis/ability status, appearance or body size will not be tolerated.  


> The material in this code of conduct is derived from "[Bahlai Lab Project Management](https://github.com/BahlaiLab/Policies/blob/master/Code_of_conduct.md)" by Dr. Christie Bahlai, used under CC BY 4.0. 
